foto/config/routes.rb
Foto::Application.routes.draw do
  resources :personas

end

foto/app/models/persona.rb
class Persona < ActiveRecord::Base
  attr_accessible :email, :fch_ncto, :identificacion, :municipio, :nombre, :telefono, :avatar

  has_attached_file :avatar, :styles => { :small => "150x150>", :lsmall => "30x30>" },
                  :url  => "/assets/personas/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/personas/:id/:style/:basename.:extension"

validates_attachment_presence :avatar
validates_attachment_size :avatar, :less_than => 5.megabytes
validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']
end

foto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

foto/app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @personas }
    end
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
    @persona = Persona.find(params[:id])

      # Change the filename of the downloaded pdf file
   headers["Content-Disposition"] = 
   "attachment; filename=\"#{@persona.nombre}\""
   
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @persona }
    end
  end

  # GET /personas/new
  # GET /personas/new.json
  def new
    @persona = Persona.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @persona }
    end
  end

  # GET /personas/1/edit
  def edit
    @persona = Persona.find(params[:id])
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(params[:persona])

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render json: @persona, status: :created, location: @persona }
      else
        format.html { render action: "new" }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /personas/1
  # PUT /personas/1.json
  def update
    @persona = Persona.find(params[:id])

    respond_to do |format|
      if @persona.update_attributes(params[:persona])
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona = Persona.find(params[:id])
    @persona.destroy

    respond_to do |format|
      format.html { redirect_to personas_url }
      format.json { head :no_content }
    end
  end
end

foto/app/helpers/application_helper.rb
module ApplicationHelper
end

foto/app/helpers/personas_helper.rb
module PersonasHelper
end

foto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

foto/app/views/personas/_form.html.erb
<%= simple_form_for @persona, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
 
  
  <%= f.input :nombre %>
    <%= image_tag @persona.avatar.url(:small) %>
  <%= f.label :Foto  %>
  <%= f.file_field :avatar %>
  <%= f.input :identificacion %>
  <%= f.input :email %>
  <%= f.input :fch_ncto %>
  <%= f.input :telefono %>
  <%= f.input :municipio %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                personas_path, :class => 'btn' %>
  </div>
<% end %>

foto/app/views/personas/edit.html.erb
<%- model_class = Persona -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

foto/app/views/personas/index.html.erb
<%- model_class = Persona -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>

      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:identificacion) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:fch_ncto) %></th>
      <th><%= model_class.human_attribute_name(:telefono) %></th>
      <th><%= model_class.human_attribute_name(:municipio) %></th>
      
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= link_to persona.id, persona_path(persona) %></td>
        <td><%= image_tag persona.avatar.url(:lsmall) %> <%= persona.nombre %></td>
        <td><%= persona.identificacion %></td>
        <td><%= persona.email %></td>
        <td><%= persona.fch_ncto %></td>
        <td><%= persona.telefono %></td>
        <td><%= persona.municipio %></td>
        
       
        <td>
          <%= link_to "PDF", persona, :class => 'btn btn-mini' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_persona_path(persona), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      persona_path(persona),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_persona_path,
            :class => 'btn btn-primary' %>

foto/app/views/personas/new.html.erb
<%- model_class = Persona -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

foto/app/views/personas/show.html.erb
<%- model_class = Persona -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>





<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @persona.nombre %></dd>
  <dt><strong><%= image_tag @persona.avatar.url(:small) %></strong></dt>
  <dt><strong><%= model_class.human_attribute_name(:identificacion) %>:</strong></dt>
  <dd><%= @persona.identificacion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @persona.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fch_ncto) %>:</strong></dt>
  <dd><%= @persona.fch_ncto %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefono) %>:</strong></dt>
  <dd><%= @persona.telefono %></dd>
  <dt><strong><%= model_class.human_attribute_name(:municipio) %>:</strong></dt>
  <dd><%= @persona.municipio %></dd>
  



<p id="pdf_link"><%= link_to "Download Invoice (PDF)", persona_path(@persona, :format => "pdf") %></p>



</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              personas_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_persona_path(@persona), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              persona_path(@persona),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>